### ISSUE TITLE
Option to get value as buffer - Support emoji

### ISSUE THREAD

**Issue by ido-pluto** [hlhr202/llama-node#4]
When you get tokens as text, some information is lost, for example, emojis that are built with more than one byte.
The token sends half an emoji, and the utf8 encodes that to an unknown character. 

I thought about possible solutions:
1. to send as a buffer to ensure no information is lost, and let the client handle it
2. if you see the last character is encoded to unknown save the byte for the next token.

I implement the second solution for something similar, maybe it could help
[massage-builder](https://github.com/ido-pluto/catai/blob/5d30d7eb9924a2e778d7f8e6e7ab91745b0465d6/server/src/message-builder.js)

**Comment by hlhr202** [comment]
@ido-pluto Hi I guess currently I m not able to support this buffer transfer. since inference callback in llama-rs only expose string. I m not sure how llama.cpp will do this but for rust version, emoji is probably not supported.
I will just keep observing what changes will be merged in llama-rs repo and see if there is a possibility to do this.

**Comment by ido-pluto** [comment]
Currently, the process will crash if the model tries to print emojis:
```
Here are some emojis: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: None }', packages/llama-cpp/src/context.rs:115:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```json
"@llama-node/llama-cpp": "^0.0.27",
"llama-node": "^0.0.27",
```

**Comment by hlhr202** [comment]
> Currently, the process will crash if the model tries to print emojis:
> 
> ```
> Here are some emojis: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 0, error_len: None }', packages/llama-cpp/src/context.rs:115:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> ```json
> "@llama-node/llama-cpp": "^0.0.27",
> "llama-node": "^0.0.27",
> ```

ok will look into this

**Comment by hlhr202** [comment]
@ido-pluto 
I can only fix for unsupported utf-8, it will be replaced by '�' token.
But if you don want to see this, please follow llama.cpp's new converter as follow. It seems to have fixed the problem.
https://github.com/ggerganov/llama.cpp/pull/79/files

For llama-node, we can only do replacement to avoid panic, the changes I have put it here.
https://github.com/Atome-FE/llama-node/commit/5d552dff06a9279addcf568aa840c2a69ac992c9
